package exception;

public class Exam03 {
public static void main(String[] args) {
	
	try {
		
	} catch (Exception e) {
		
	}finally { //오류가 나도 안나도 실행할 소스 실행
		
	}
}
}
